language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

script: phpunit --configuration phpunit.travis.xml --coverage-text
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover